package:
    name: xtl
    version: 0.3.6
source:
    fn: xtl-0.3.6.tar.gz
    sha256: 37f5ba13d4e73d9ff74d9a01d72ec0a58ad237933ae2ccdba0746dbe325aadc3
    url: https://github.com/QuantStack/xtl/archive/0.3.6.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
    skip: true  # [win and py<35]
    features:   # [win]
      - vc14    # [win]
requirements:
    build:
        - cmake
        - toolchain
    run: []
test:
    commands:
        - if not exist %LIBRARY_INC%\\xtl\\xbasic_fixed_string.hpp exit 1        # [win]
        - if not exist %LIBRARY_LIB%\\cmake\\xtl\\xtlConfig.cmake exit 1         # [win]
        - if not exist %LIBRARY_LIB%\\cmake\\xtl\\xtlConfigVersion.cmake exit 1  # [win]
        - test -f ${PREFIX}/include/xtl/xbasic_fixed_string.hpp                  # [unix]
        - test -f ${PREFIX}/lib/cmake/xtl/xtlConfig.cmake                        # [unix]
        - test -f ${PREFIX}/lib/cmake/xtl/xtlConfigVersion.cmake                 # [unix]
about:
    description: Basic tools (containers, algorithms) used by other packages from
        Quantstack
    dev_url: https://github.com/QuantStack/xtl
    doc_url: http://xtl.readthedocs.io
    home: http://quantstack.net
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: The QuantStack tools library
extra:
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - JohanMabille
        - gouarin